#
# Automatically generated file. DO NOT MODIFY
#

PRODUCT_SOONG_NAMESPACES += \
    vendor/10or/G

PRODUCT_COPY_FILES += \
    vendor/10or/G/proprietary/etc/permissions/privapp-permissions-qti.xml:$(TARGET_COPY_OUT_ETC)/permissions/privapp-permissions-qti.xml \
    vendor/10or/G/proprietary/etc/sysconfig/qti_whitelist.xml:$(TARGET_COPY_OUT_ETC)/sysconfig/qti_whitelist.xml \
    vendor/10or/G/proprietary/product/etc/permissions/telephony_product_privapp-permissions-qti.xml:$(TARGET_COPY_OUT_PRODUCT)/etc/permissions/telephony_product_privapp-permissions-qti.xml \
    vendor/10or/G/proprietary/system_ext/etc/dpm/dpm.conf:$(TARGET_COPY_OUT_SYSTEM_EXT)/etc/dpm/dpm.conf \
    vendor/10or/G/proprietary/system_ext/etc/init/dpmd.rc:$(TARGET_COPY_OUT_SYSTEM_EXT)/etc/init/dpmd.rc \
    vendor/10or/G/proprietary/system_ext/etc/permissions/com.qti.dpmframework.xml:$(TARGET_COPY_OUT_SYSTEM_EXT)/etc/permissions/com.qti.dpmframework.xml \
    vendor/10or/G/proprietary/system_ext/etc/permissions/dpmapi.xml:$(TARGET_COPY_OUT_SYSTEM_EXT)/etc/permissions/dpmapi.xml \
    vendor/10or/G/proprietary/system_ext/etc/permissions/qcrilhook.xml:$(TARGET_COPY_OUT_SYSTEM_EXT)/etc/permissions/qcrilhook.xml \
    vendor/10or/G/proprietary/system_ext/etc/permissions/qti_libpermissions.xml:$(TARGET_COPY_OUT_SYSTEM_EXT)/etc/permissions/qti_libpermissions.xml \
    vendor/10or/G/proprietary/system_ext/etc/permissions/qti_permissions.xml:$(TARGET_COPY_OUT_SYSTEM_EXT)/etc/permissions/qti_permissions.xml \
    vendor/10or/G/proprietary/system_ext/etc/permissions/telephony_system-ext_privapp-permissions-qti.xml:$(TARGET_COPY_OUT_SYSTEM_EXT)/etc/permissions/telephony_system-ext_privapp-permissions-qti.xml \
    vendor/10or/G/proprietary/system_ext/etc/permissions/telephonyservice.xml:$(TARGET_COPY_OUT_SYSTEM_EXT)/etc/permissions/telephonyservice.xml \
    vendor/10or/G/proprietary/vendor/etc/acdbdata/QRD/QRD_Bluetooth_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/QRD/QRD_Bluetooth_cal.acdb \
    vendor/10or/G/proprietary/vendor/etc/acdbdata/QRD/QRD_General_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/QRD/QRD_General_cal.acdb \
    vendor/10or/G/proprietary/vendor/etc/acdbdata/QRD/QRD_Global_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/QRD/QRD_Global_cal.acdb \
    vendor/10or/G/proprietary/vendor/etc/acdbdata/QRD/QRD_Handset_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/QRD/QRD_Handset_cal.acdb \
    vendor/10or/G/proprietary/vendor/etc/acdbdata/QRD/QRD_Hdmi_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/QRD/QRD_Hdmi_cal.acdb \
    vendor/10or/G/proprietary/vendor/etc/acdbdata/QRD/QRD_Headset_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/QRD/QRD_Headset_cal.acdb \
    vendor/10or/G/proprietary/vendor/etc/acdbdata/QRD/QRD_Speaker_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/QRD/QRD_Speaker_cal.acdb \
    vendor/10or/G/proprietary/vendor/etc/acdbdata/QRD/QRD_workspaceFile.qwsp:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/QRD/QRD_workspaceFile.qwsp \
    vendor/10or/G/proprietary/vendor/etc/camera/camera_config.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/camera_config.xml \
    vendor/10or/G/proprietary/vendor/etc/camera/ov13358_cbahc13_mono_chromatix.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/ov13358_cbahc13_mono_chromatix.xml \
    vendor/10or/G/proprietary/vendor/etc/camera/ov13358_ohs0544_mono_chromatix.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/ov13358_ohs0544_mono_chromatix.xml \
    vendor/10or/G/proprietary/vendor/etc/camera/ov13855_cbahc14_chromatix.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/ov13855_cbahc14_chromatix.xml \
    vendor/10or/G/proprietary/vendor/etc/camera/ov13855_ohs0544_chromatix.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/ov13855_ohs0544_chromatix.xml \
    vendor/10or/G/proprietary/vendor/etc/camera/ov16885_sunny_chromatix.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/ov16885_sunny_chromatix.xml \
    vendor/10or/G/proprietary/vendor/etc/camera/s5k3p8_chromatix.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/s5k3p8_chromatix.xml \
    vendor/10or/G/proprietary/vendor/etc/cne/mwqem.conf:$(TARGET_COPY_OUT_VENDOR)/etc/cne/mwqem.conf \
    vendor/10or/G/proprietary/vendor/etc/cne/profileMwqem.xml:$(TARGET_COPY_OUT_VENDOR)/etc/cne/profileMwqem.xml \
    vendor/10or/G/proprietary/vendor/etc/cne/wqeclient/ATT/ATT_profile1.xml:$(TARGET_COPY_OUT_VENDOR)/etc/cne/wqeclient/ATT/ATT_profile1.xml \
    vendor/10or/G/proprietary/vendor/etc/cne/wqeclient/ATT/ATT_profile2.xml:$(TARGET_COPY_OUT_VENDOR)/etc/cne/wqeclient/ATT/ATT_profile2.xml \
    vendor/10or/G/proprietary/vendor/etc/cne/wqeclient/ATT/ATT_profile3.xml:$(TARGET_COPY_OUT_VENDOR)/etc/cne/wqeclient/ATT/ATT_profile3.xml \
    vendor/10or/G/proprietary/vendor/etc/cne/wqeclient/ATT/ATT_profile4.xml:$(TARGET_COPY_OUT_VENDOR)/etc/cne/wqeclient/ATT/ATT_profile4.xml \
    vendor/10or/G/proprietary/vendor/etc/cne/wqeclient/ATT/ATT_profile5.xml:$(TARGET_COPY_OUT_VENDOR)/etc/cne/wqeclient/ATT/ATT_profile5.xml \
    vendor/10or/G/proprietary/vendor/etc/cne/wqeclient/ATT/ATT_profile6.xml:$(TARGET_COPY_OUT_VENDOR)/etc/cne/wqeclient/ATT/ATT_profile6.xml \
    vendor/10or/G/proprietary/vendor/etc/cne/wqeclient/ROW/ROW_profile1.xml:$(TARGET_COPY_OUT_VENDOR)/etc/cne/wqeclient/ROW/ROW_profile1.xml \
    vendor/10or/G/proprietary/vendor/etc/cne/wqeclient/ROW/ROW_profile15.xml:$(TARGET_COPY_OUT_VENDOR)/etc/cne/wqeclient/ROW/ROW_profile15.xml \
    vendor/10or/G/proprietary/vendor/etc/cne/wqeclient/ROW/ROW_profile16.xml:$(TARGET_COPY_OUT_VENDOR)/etc/cne/wqeclient/ROW/ROW_profile16.xml \
    vendor/10or/G/proprietary/vendor/etc/cne/wqeclient/ROW/ROW_profile17.xml:$(TARGET_COPY_OUT_VENDOR)/etc/cne/wqeclient/ROW/ROW_profile17.xml \
    vendor/10or/G/proprietary/vendor/etc/cne/wqeclient/ROW/ROW_profile18.xml:$(TARGET_COPY_OUT_VENDOR)/etc/cne/wqeclient/ROW/ROW_profile18.xml \
    vendor/10or/G/proprietary/vendor/etc/cne/wqeclient/ROW/ROW_profile19.xml:$(TARGET_COPY_OUT_VENDOR)/etc/cne/wqeclient/ROW/ROW_profile19.xml \
    vendor/10or/G/proprietary/vendor/etc/cne/wqeclient/ROW/ROW_profile2.xml:$(TARGET_COPY_OUT_VENDOR)/etc/cne/wqeclient/ROW/ROW_profile2.xml \
    vendor/10or/G/proprietary/vendor/etc/cne/wqeclient/ROW/ROW_profile20.xml:$(TARGET_COPY_OUT_VENDOR)/etc/cne/wqeclient/ROW/ROW_profile20.xml \
    vendor/10or/G/proprietary/vendor/etc/cne/wqeclient/ROW/ROW_profile21.xml:$(TARGET_COPY_OUT_VENDOR)/etc/cne/wqeclient/ROW/ROW_profile21.xml \
    vendor/10or/G/proprietary/vendor/etc/cne/wqeclient/ROW/ROW_profile3.xml:$(TARGET_COPY_OUT_VENDOR)/etc/cne/wqeclient/ROW/ROW_profile3.xml \
    vendor/10or/G/proprietary/vendor/etc/cne/wqeclient/ROW/ROW_profile32.xml:$(TARGET_COPY_OUT_VENDOR)/etc/cne/wqeclient/ROW/ROW_profile32.xml \
    vendor/10or/G/proprietary/vendor/etc/cne/wqeclient/ROW/ROW_profile4.xml:$(TARGET_COPY_OUT_VENDOR)/etc/cne/wqeclient/ROW/ROW_profile4.xml \
    vendor/10or/G/proprietary/vendor/etc/cne/wqeclient/ROW/ROW_profile5.xml:$(TARGET_COPY_OUT_VENDOR)/etc/cne/wqeclient/ROW/ROW_profile5.xml \
    vendor/10or/G/proprietary/vendor/etc/cne/wqeclient/ROW/ROW_profile6.xml:$(TARGET_COPY_OUT_VENDOR)/etc/cne/wqeclient/ROW/ROW_profile6.xml \
    vendor/10or/G/proprietary/vendor/etc/cne/wqeclient/ROW/ROW_profile7.xml:$(TARGET_COPY_OUT_VENDOR)/etc/cne/wqeclient/ROW/ROW_profile7.xml \
    vendor/10or/G/proprietary/vendor/etc/cne/wqeclient/VZW/VZW_profile1.xml:$(TARGET_COPY_OUT_VENDOR)/etc/cne/wqeclient/VZW/VZW_profile1.xml \
    vendor/10or/G/proprietary/vendor/etc/cne/wqeclient/VZW/VZW_profile2.xml:$(TARGET_COPY_OUT_VENDOR)/etc/cne/wqeclient/VZW/VZW_profile2.xml \
    vendor/10or/G/proprietary/vendor/etc/cne/wqeclient/VZW/VZW_profile3.xml:$(TARGET_COPY_OUT_VENDOR)/etc/cne/wqeclient/VZW/VZW_profile3.xml \
    vendor/10or/G/proprietary/vendor/etc/cne/wqeclient/VZW/VZW_profile4.xml:$(TARGET_COPY_OUT_VENDOR)/etc/cne/wqeclient/VZW/VZW_profile4.xml \
    vendor/10or/G/proprietary/vendor/etc/cne/wqeclient/VZW/VZW_profile5.xml:$(TARGET_COPY_OUT_VENDOR)/etc/cne/wqeclient/VZW/VZW_profile5.xml \
    vendor/10or/G/proprietary/vendor/etc/cne/wqeclient/VZW/VZW_profile6.xml:$(TARGET_COPY_OUT_VENDOR)/etc/cne/wqeclient/VZW/VZW_profile6.xml \
    vendor/10or/G/proprietary/vendor/etc/data/dsi_config.xml:$(TARGET_COPY_OUT_VENDOR)/etc/data/dsi_config.xml \
    vendor/10or/G/proprietary/vendor/etc/data/netmgr_config.xml:$(TARGET_COPY_OUT_VENDOR)/etc/data/netmgr_config.xml \
    vendor/10or/G/proprietary/vendor/etc/default-permissions/com.qualcomm.qti.cne.xml:$(TARGET_COPY_OUT_VENDOR)/etc/default-permissions/com.qualcomm.qti.cne.xml \
    vendor/10or/G/proprietary/vendor/etc/init/android.hardware.bluetooth@1.0-service-qti.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/android.hardware.bluetooth@1.0-service-qti.rc \
    vendor/10or/G/proprietary/vendor/etc/init/android.hardware.drm@1.3-service.widevine.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/android.hardware.drm@1.3-service.widevine.rc \
    vendor/10or/G/proprietary/vendor/etc/init/android.hardware.gnss@2.0-service-qti.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/android.hardware.gnss@2.0-service-qti.rc \
    vendor/10or/G/proprietary/vendor/etc/init/cnd.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/cnd.rc \
    vendor/10or/G/proprietary/vendor/etc/init/dataadpl.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/dataadpl.rc \
    vendor/10or/G/proprietary/vendor/etc/init/dataqti.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/dataqti.rc \
    vendor/10or/G/proprietary/vendor/etc/init/dpmQmiMgr.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/dpmQmiMgr.rc \
    vendor/10or/G/proprietary/vendor/etc/init/ims_rtp_daemon_legacy.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/ims_rtp_daemon_legacy.rc \
    vendor/10or/G/proprietary/vendor/etc/init/imsdatadaemon.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/imsdatadaemon.rc \
    vendor/10or/G/proprietary/vendor/etc/init/imsqmidaemon.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/imsqmidaemon.rc \
    vendor/10or/G/proprietary/vendor/etc/init/imsrcsd.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/imsrcsd.rc \
    vendor/10or/G/proprietary/vendor/etc/init/init-qcril-data.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/init-qcril-data.rc \
    vendor/10or/G/proprietary/vendor/etc/init/init.time_daemon.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/init.time_daemon.rc \
    vendor/10or/G/proprietary/vendor/etc/init/init_thermal-engine.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/init_thermal-engine.rc \
    vendor/10or/G/proprietary/vendor/etc/init/netmgrd.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/netmgrd.rc \
    vendor/10or/G/proprietary/vendor/etc/init/port-bridge.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/port-bridge.rc \
    vendor/10or/G/proprietary/vendor/etc/init/qcrild.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/qcrild.rc \
    vendor/10or/G/proprietary/vendor/etc/init/vendor.display.color@1.0-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.display.color@1.0-service.rc \
    vendor/10or/G/proprietary/vendor/etc/init/vendor.qti.hardware.alarm@1.0-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.qti.hardware.alarm@1.0-service.rc \
    vendor/10or/G/proprietary/vendor/etc/init/vendor.qti.hardware.perf@2.0-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.qti.hardware.perf@2.0-service.rc \
    vendor/10or/G/proprietary/vendor/etc/init/vendor.qti.rmt_storage.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.qti.rmt_storage.rc \
    vendor/10or/G/proprietary/vendor/etc/init/vendor.qti.tftp.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.qti.tftp.rc \
    vendor/10or/G/proprietary/vendor/etc/msm_irqbalance.conf:$(TARGET_COPY_OUT_VENDOR)/etc/msm_irqbalance.conf \
    vendor/10or/G/proprietary/vendor/etc/qmi_fw.conf:$(TARGET_COPY_OUT_VENDOR)/etc/qmi_fw.conf \
    vendor/10or/G/proprietary/vendor/etc/sec_config:$(TARGET_COPY_OUT_VENDOR)/etc/sec_config \
    vendor/10or/G/proprietary/vendor/etc/seccomp_policy/atfwd@2.0.policy:$(TARGET_COPY_OUT_VENDOR)/etc/seccomp_policy/atfwd@2.0.policy \
    vendor/10or/G/proprietary/vendor/etc/seccomp_policy/imsrtp.policy:$(TARGET_COPY_OUT_VENDOR)/etc/seccomp_policy/imsrtp.policy \
    vendor/10or/G/proprietary/vendor/etc/seccomp_policy/mediacodec.policy:$(TARGET_COPY_OUT_VENDOR)/etc/seccomp_policy/mediacodec.policy \
    vendor/10or/G/proprietary/vendor/etc/seccomp_policy/mediaextractor.policy:$(TARGET_COPY_OUT_VENDOR)/etc/seccomp_policy/mediaextractor.policy \
    vendor/10or/G/proprietary/vendor/etc/sensors/hals.conf:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/hals.conf \
    vendor/10or/G/proprietary/vendor/firmware/a530_pfp.fw:$(TARGET_COPY_OUT_VENDOR)/firmware/a530_pfp.fw \
    vendor/10or/G/proprietary/vendor/firmware/a530_pm4.fw:$(TARGET_COPY_OUT_VENDOR)/firmware/a530_pm4.fw \
    vendor/10or/G/proprietary/vendor/firmware/cpp_firmware_v1_5_0.fw:$(TARGET_COPY_OUT_VENDOR)/firmware/cpp_firmware_v1_5_0.fw \
    vendor/10or/G/proprietary/vendor/radio/qcril_database/qcril.db:$(TARGET_COPY_OUT_VENDOR)/radio/qcril_database/qcril.db \
    vendor/10or/G/proprietary/vendor/radio/qcril_database/upgrade/0_initial.sql:$(TARGET_COPY_OUT_VENDOR)/radio/qcril_database/upgrade/0_initial.sql \
    vendor/10or/G/proprietary/vendor/radio/qcril_database/upgrade/1_version_intro.sql:$(TARGET_COPY_OUT_VENDOR)/radio/qcril_database/upgrade/1_version_intro.sql \
    vendor/10or/G/proprietary/vendor/radio/qcril_database/upgrade/2_version_add_wps_config.sql:$(TARGET_COPY_OUT_VENDOR)/radio/qcril_database/upgrade/2_version_add_wps_config.sql \
    vendor/10or/G/proprietary/vendor/radio/qcril_database/upgrade/3_version_update_wps_config.sql:$(TARGET_COPY_OUT_VENDOR)/radio/qcril_database/upgrade/3_version_update_wps_config.sql \
    vendor/10or/G/proprietary/vendor/radio/qcril_database/upgrade/4_version_update_ecc_table.sql:$(TARGET_COPY_OUT_VENDOR)/radio/qcril_database/upgrade/4_version_update_ecc_table.sql \
    vendor/10or/G/proprietary/vendor/radio/qcril_database/upgrade/5_version_update_ecc_table.sql:$(TARGET_COPY_OUT_VENDOR)/radio/qcril_database/upgrade/5_version_update_ecc_table.sql

PRODUCT_PACKAGES += \
    eglSubDriverAndroid \
    libEGL_adreno \
    libGLESv1_CM_adreno \
    libGLESv2_adreno \
    libq3dtools_adreno \
    libq3dtools_esx \
    vulkan.adreno \
    libC2D2 \
    libOpenCL \
    libQSEEComAPI \
    libadreno_utils \
    libadsp_default_listener \
    libadsprpc \
    libc2d30_bltlib \
    libdiag \
    libdisp-aba \
    libdsutils \
    libfastcvadsp_stub \
    libfastcvopt \
    libgsl \
    libidl \
    libllvm-glnext \
    libmdmdetect \
    libmdsprpc \
    libmm-hdcpmgr \
    libmmosal \
    libpdmapper \
    libperfconfig \
    libperfgluelayer \
    libpvr \
    libqcci_legacy \
    libqdi \
    libqdp \
    libqmi \
    libqmi_cci \
    libqmi_client_helper \
    libqmi_client_qmux \
    libqmi_common_so \
    libqmi_csi \
    libqmi_encdec \
    libqmi_legacy \
    libqmiservices \
    libqti-perfd-client \
    libqti-perfd \
    libqti-util \
    libremosaic_daemon \
    libremosaiclib \
    libscalar \
    libsdsprpc \
    libsensor1 \
    libsensor_reg \
    libsensor_user_cal \
    libthermalclient \
    libvpplibrary \
    sensors.ssc \
    vendor.qti.hardware.qdutils_disp@1.0 \
    libAltek_AF \
    libHAFIAFalSDE1 \
    libIAFalSDE1 \
    libIQM_OTP_Correction \
    libIQ_Match_Lib \
    libacdb-fts \
    libacdbloader \
    libacdbrtac \
    libactuator_dw9800w \
    libactuator_dw9800w_cbahc13 \
    libactuator_dw9800w_cbahc14 \
    libadiertac \
    libadm \
    libadpcmdec \
    libalCMotion \
    libaudcal \
    libaudioalsa \
    libchromaflash \
    libchromatix_ov13358_cbahc13_mono_common \
    libchromatix_ov13358_cbahc13_mono_cpp_hfr_120 \
    libchromatix_ov13358_cbahc13_mono_cpp_hfr_60 \
    libchromatix_ov13358_cbahc13_mono_cpp_hfr_90 \
    libchromatix_ov13358_cbahc13_mono_cpp_liveshot \
    libchromatix_ov13358_cbahc13_mono_cpp_preview \
    libchromatix_ov13358_cbahc13_mono_cpp_snapshot \
    libchromatix_ov13358_cbahc13_mono_cpp_video \
    libchromatix_ov13358_cbahc13_mono_default_preview_dw9800w_cbahc14 \
    libchromatix_ov13358_cbahc13_mono_default_video_dw9800w_cbahc14 \
    libchromatix_ov13358_cbahc13_mono_hfr_120 \
    libchromatix_ov13358_cbahc13_mono_hfr_120_dw9800w_cbahc14 \
    libchromatix_ov13358_cbahc13_mono_hfr_60 \
    libchromatix_ov13358_cbahc13_mono_hfr_60_dw9800w_cbahc14 \
    libchromatix_ov13358_cbahc13_mono_hfr_90 \
    libchromatix_ov13358_cbahc13_mono_hfr_90_dw9800w_cbahc14 \
    libchromatix_ov13358_cbahc13_mono_liveshot \
    libchromatix_ov13358_cbahc13_mono_postproc \
    libchromatix_ov13358_cbahc13_mono_preview \
    libchromatix_ov13358_cbahc13_mono_snapshot \
    libchromatix_ov13358_cbahc13_mono_video \
    libchromatix_ov13358_cbahc13_mono_zsl_preview_dw9800w_cbahc14 \
    libchromatix_ov13358_cbahc13_mono_zsl_video_dw9800w_cbahc14 \
    libchromatix_ov13358_ohs0544_mono_common \
    libchromatix_ov13358_ohs0544_mono_cpp_hfr_120 \
    libchromatix_ov13358_ohs0544_mono_cpp_hfr_60 \
    libchromatix_ov13358_ohs0544_mono_cpp_hfr_90 \
    libchromatix_ov13358_ohs0544_mono_cpp_liveshot \
    libchromatix_ov13358_ohs0544_mono_cpp_preview \
    libchromatix_ov13358_ohs0544_mono_cpp_snapshot \
    libchromatix_ov13358_ohs0544_mono_cpp_video \
    libchromatix_ov13358_ohs0544_mono_default_preview_dw9800w \
    libchromatix_ov13358_ohs0544_mono_default_video_dw9800w \
    libchromatix_ov13358_ohs0544_mono_hfr_120 \
    libchromatix_ov13358_ohs0544_mono_hfr_120_dw9800w \
    libchromatix_ov13358_ohs0544_mono_hfr_60 \
    libchromatix_ov13358_ohs0544_mono_hfr_60_dw9800w \
    libchromatix_ov13358_ohs0544_mono_hfr_90 \
    libchromatix_ov13358_ohs0544_mono_hfr_90_dw9800w \
    libchromatix_ov13358_ohs0544_mono_liveshot \
    libchromatix_ov13358_ohs0544_mono_postproc \
    libchromatix_ov13358_ohs0544_mono_preview \
    libchromatix_ov13358_ohs0544_mono_snapshot \
    libchromatix_ov13358_ohs0544_mono_video \
    libchromatix_ov13358_ohs0544_mono_zsl_preview_dw9800w \
    libchromatix_ov13358_ohs0544_mono_zsl_video_dw9800w \
    libchromatix_ov13855_cbahc14_common \
    libchromatix_ov13855_cbahc14_cpp_hfr_120 \
    libchromatix_ov13855_cbahc14_cpp_hfr_60 \
    libchromatix_ov13855_cbahc14_cpp_hfr_90 \
    libchromatix_ov13855_cbahc14_cpp_liveshot \
    libchromatix_ov13855_cbahc14_cpp_preview \
    libchromatix_ov13855_cbahc14_cpp_snapshot \
    libchromatix_ov13855_cbahc14_cpp_video \
    libchromatix_ov13855_cbahc14_default_preview_dw9800w_cbahc14 \
    libchromatix_ov13855_cbahc14_default_video_dw9800w_cbahc14 \
    libchromatix_ov13855_cbahc14_hfr_120 \
    libchromatix_ov13855_cbahc14_hfr_120_dw9800w_cbahc14 \
    libchromatix_ov13855_cbahc14_hfr_60 \
    libchromatix_ov13855_cbahc14_hfr_60_dw9800w_cbahc14 \
    libchromatix_ov13855_cbahc14_hfr_90 \
    libchromatix_ov13855_cbahc14_hfr_90_dw9800w_cbahc14 \
    libchromatix_ov13855_cbahc14_liveshot \
    libchromatix_ov13855_cbahc14_postproc \
    libchromatix_ov13855_cbahc14_preview \
    libchromatix_ov13855_cbahc14_snapshot \
    libchromatix_ov13855_cbahc14_video \
    libchromatix_ov13855_cbahc14_zsl_preview_dw9800w_cbahc14 \
    libchromatix_ov13855_cbahc14_zsl_video_dw9800w_cbahc14 \
    libchromatix_ov13855_ohs0544_common \
    libchromatix_ov13855_ohs0544_cpp_hfr_120 \
    libchromatix_ov13855_ohs0544_cpp_hfr_60 \
    libchromatix_ov13855_ohs0544_cpp_hfr_90 \
    libchromatix_ov13855_ohs0544_cpp_liveshot \
    libchromatix_ov13855_ohs0544_cpp_preview \
    libchromatix_ov13855_ohs0544_cpp_snapshot \
    libchromatix_ov13855_ohs0544_cpp_video \
    libchromatix_ov13855_ohs0544_default_preview_dw9800w \
    libchromatix_ov13855_ohs0544_default_video_dw9800w \
    libchromatix_ov13855_ohs0544_hfr_120 \
    libchromatix_ov13855_ohs0544_hfr_120_dw9800w \
    libchromatix_ov13855_ohs0544_hfr_60 \
    libchromatix_ov13855_ohs0544_hfr_60_dw9800w \
    libchromatix_ov13855_ohs0544_hfr_90 \
    libchromatix_ov13855_ohs0544_hfr_90_dw9800w \
    libchromatix_ov13855_ohs0544_liveshot \
    libchromatix_ov13855_ohs0544_postproc \
    libchromatix_ov13855_ohs0544_preview \
    libchromatix_ov13855_ohs0544_snapshot \
    libchromatix_ov13855_ohs0544_video \
    libchromatix_ov13855_ohs0544_zsl_preview_dw9800w \
    libchromatix_ov13855_ohs0544_zsl_video_dw9800w \
    libchromatix_ov16885_sunny_common \
    libchromatix_ov16885_sunny_cpp_hfr_120 \
    libchromatix_ov16885_sunny_cpp_hfr_60 \
    libchromatix_ov16885_sunny_cpp_hfr_90 \
    libchromatix_ov16885_sunny_cpp_liveshot \
    libchromatix_ov16885_sunny_cpp_preview \
    libchromatix_ov16885_sunny_cpp_snapshot \
    libchromatix_ov16885_sunny_cpp_video \
    libchromatix_ov16885_sunny_default_preview_nolens \
    libchromatix_ov16885_sunny_default_video \
    libchromatix_ov16885_sunny_default_video_nolens \
    libchromatix_ov16885_sunny_hfr_120 \
    libchromatix_ov16885_sunny_hfr_120_nolens \
    libchromatix_ov16885_sunny_hfr_60 \
    libchromatix_ov16885_sunny_hfr_60_nolens \
    libchromatix_ov16885_sunny_hfr_90 \
    libchromatix_ov16885_sunny_hfr_90_nolens \
    libchromatix_ov16885_sunny_postproc \
    libchromatix_ov16885_sunny_preview \
    libchromatix_ov16885_sunny_snapshot \
    libchromatix_ov16885_sunny_zsl_preview_nolens \
    libchromatix_ov16885_sunny_zsl_video_nolens \
    libchromatix_s5k3p8_common \
    libchromatix_s5k3p8_cpp_hfr_120 \
    libchromatix_s5k3p8_cpp_hfr_60 \
    libchromatix_s5k3p8_cpp_hfr_90 \
    libchromatix_s5k3p8_cpp_liveshot \
    libchromatix_s5k3p8_cpp_preview \
    libchromatix_s5k3p8_cpp_snapshot \
    libchromatix_s5k3p8_cpp_video \
    libchromatix_s5k3p8_default_preview_bu64297 \
    libchromatix_s5k3p8_default_video \
    libchromatix_s5k3p8_default_video_bu64297 \
    libchromatix_s5k3p8_hfr_120 \
    libchromatix_s5k3p8_hfr_120_bu64297 \
    libchromatix_s5k3p8_hfr_60 \
    libchromatix_s5k3p8_hfr_60_bu64297 \
    libchromatix_s5k3p8_hfr_90 \
    libchromatix_s5k3p8_hfr_90_bu64297 \
    libchromatix_s5k3p8_postproc \
    libchromatix_s5k3p8_preview \
    libchromatix_s5k3p8_snapshot \
    libchromatix_s5k3p8_zsl_preview_bu64297 \
    libchromatix_s5k3p8_zsl_video_bu64297 \
    libdrc \
    libfcell \
    libflash_pmic \
    libjpegdhw \
    libjpegdmahw \
    libjpegehw \
    libmmcamera2_c2d_module \
    libmmcamera2_cpp_module \
    libmmcamera2_dcrf \
    libmmcamera2_frame_algorithm \
    libmmcamera2_iface_modules \
    libmmcamera2_imglib_modules \
    libmmcamera2_is \
    libmmcamera2_isp_modules \
    libmmcamera2_mct \
    libmmcamera2_mct_shimlayer \
    libmmcamera2_pp_buf_mgr \
    libmmcamera2_pproc_modules \
    libmmcamera2_q3a_core \
    libmmcamera2_sensor_modules \
    libmmcamera2_stats_algorithm \
    libmmcamera2_stats_modules \
    libmmcamera_cac3_lib \
    libmmcamera_chromaflash_lib \
    libmmcamera_dbg \
    libmmcamera_dcrf_lib \
    libmmcamera_dummyalgo \
    libmmcamera_eebinparse \
    libmmcamera_eeprom_util \
    libmmcamera_eztune_module \
    libmmcamera_facedetection_lib \
    libmmcamera_faceproc \
    libmmcamera_faceproc2 \
    libmmcamera_hdr_gb_lib \
    libmmcamera_imglib \
    libmmcamera_isp_abf40 \
    libmmcamera_isp_bcc40 \
    libmmcamera_isp_be_stats44 \
    libmmcamera_isp_bf_stats47 \
    libmmcamera_isp_bg_stats44 \
    libmmcamera_isp_bhist_stats44 \
    libmmcamera_isp_bpc40 \
    libmmcamera_isp_chroma_enhan40 \
    libmmcamera_isp_chroma_suppress40 \
    libmmcamera_isp_clamp_encoder40 \
    libmmcamera_isp_clamp_video40 \
    libmmcamera_isp_clamp_viewfinder40 \
    libmmcamera_isp_color_correct40 \
    libmmcamera_isp_color_xform_encoder40 \
    libmmcamera_isp_color_xform_viewfinder40 \
    libmmcamera_isp_cs_stats44 \
    libmmcamera_isp_demosaic40 \
    libmmcamera_isp_demux40 \
    libmmcamera_isp_fovcrop_encoder40 \
    libmmcamera_isp_fovcrop_viewfinder40 \
    libmmcamera_isp_gamma40 \
    libmmcamera_isp_ihist_stats44 \
    libmmcamera_isp_linearization40 \
    libmmcamera_isp_ltm44 \
    libmmcamera_isp_luma_adaptation40 \
    libmmcamera_isp_mce40 \
    libmmcamera_isp_mesh_rolloff40 \
    libmmcamera_isp_rs_stats44 \
    libmmcamera_isp_scaler_encoder44 \
    libmmcamera_isp_scaler_viewfinder44 \
    libmmcamera_isp_sce40 \
    libmmcamera_isp_sub_module \
    libmmcamera_isp_template \
    libmmcamera_isp_wb40 \
    libmmcamera_llvd \
    libmmcamera_optizoom_lib \
    libmmcamera_ov13358_cbahc13_mono \
    libmmcamera_ov13358_gt24c64a_chicony_eeprom \
    libmmcamera_ov13358_gt24c64a_ofg_eeprom \
    libmmcamera_ov13358_ohs0544_mono \
    libmmcamera_ov13855_cbahc14_chicony \
    libmmcamera_ov13855_gt24c64a_chicony_eeprom \
    libmmcamera_ov13855_gt24c64a_ofg_eeprom \
    libmmcamera_ov13855_ohs0544_ofg \
    libmmcamera_ov16885_fm24c64d_eeprom \
    libmmcamera_ov16885_sunny \
    libmmcamera_paaf_lib \
    libmmcamera_pdaf \
    libmmcamera_pdafcamif \
    libmmcamera_ppbase_module \
    libmmcamera_quadracfa \
    libmmcamera_s5k3p8 \
    libmmcamera_s5k3p8_fm24c64d_eeprom \
    libmmcamera_s5k3p8sp \
    libmmcamera_stillmore_lib \
    libmmcamera_sw2d_lib \
    libmmcamera_thread_services \
    libmmcamera_tintless_algo \
    libmmcamera_tintless_bg_pca_algo \
    libmmcamera_trueportrait_lib \
    libmmcamera_tuning \
    libmmcamera_tuning_lookup \
    libmmcamera_ubifocus_lib \
    libmmjpeg \
    libmmqjpeg_codec \
    libmmqjpegdma \
    libois_lc898122 \
    liboptizoom \
    libqomx_jpegdec \
    libqomx_jpegenc \
    libqomx_jpegenc_pipe \
    libseemore \
    libsmwrapper \
    libtrueportrait \
    libts_detected_face_hal \
    libts_face_beautify_hal \
    libubifocus \
    libvideoutils \
    libvqzip \
    libqcbassboost \
    libqcreverb \
    libqcvirt \
    com.qualcomm.qti.ant@1.0 \
    com.qualcomm.qti.dpm.api@1.0_vendor \
    com.qualcomm.qti.imscmservice@2.0 \
    com.qualcomm.qti.imscmservice@2.1 \
    com.qualcomm.qti.imscmservice@2.2 \
    com.qualcomm.qti.uceservice@2.0 \
    com.qualcomm.qti.uceservice@2.1 \
    com.qualcomm.qti.uceservice@2.2 \
    com.qualcomm.qti.uceservice@2.3 \
    android.hardware.bluetooth@1.0-impl-qti \
    android.hardware.gnss@2.0-impl-qti \
    gatekeeper.msm8953 \
    gf_fingerprint.goodix.default \
    keystore.msm8953 \
    vendor.qti.gnss@3.0-impl \
    vendor.qti.hardware.alarm@1.0-impl \
    vendor.qti.hardware.bluetooth_sar@1.0-impl \
    vendor.qti.hardware.btconfigstore@1.0-impl \
    lib-imsSDP \
    lib-imscmservice \
    lib-imsdpl \
    lib-imsqimf \
    lib-imsrcs-v2 \
    lib-imsrcsbaseimpl \
    lib-imsvtcore \
    lib-imsxml \
    lib-rcsconfig \
    lib-rtpcommon \
    lib-rtpcore \
    lib-rtpsl \
    lib-siputility \
    lib-uceservice \
    libGPreqcancel \
    libGPreqcancel_svc \
    libStDrvInt \
    libbatching \
    libbluetooth_audio_session_qti \
    libbt-hidlclient \
    libbtnv \
    libcacertclient \
    libcne \
    libcneapiclient \
    libcneoplookup \
    libconfigdb \
    libdataitems \
    libdpmqmihal \
    libdrmfs \
    libdrmtime \
    libdsi_netctrl \
    libgeofencing \
    libgf_algo \
    libgf_ca \
    libgf_hal \
    libgnss \
    libgnsspps \
    libgps.utils \
    libhdr_tm \
    libizat_client_api \
    libizat_core \
    liblbs_core \
    libloc_api_v02 \
    libloc_core \
    liblocation_api \
    liblocationservice \
    liblocationservice_glue \
    liblowi_client \
    liblowi_wifihal \
    liblqe \
    libnetmgr \
    libnetmgr_common \
    libnlnetmgr \
    liboemaids_vendor \
    libperipheral_client \
    libqcmaputils \
    libqcrilFramework \
    libqcrildatactl \
    libqdma_file_agent \
    libqisl \
    libqrtr \
    libqsocket \
    librcc \
    libril-qc-hal-qmi \
    libril-qc-logger \
    librilqmiservices \
    librpmb \
    libsdm-color \
    libsdm-diag \
    libsdm-disp-vndapis \
    libsdmextension \
    libsettings \
    libssd \
    libsystem_health_mon \
    libtime_genoff \
    libtinyxml2_1 \
    libvendor.goodix.hardware.fingerprint@1.0-service \
    libwms \
    libwqe \
    libwvhidl \
    libxml \
    libxtadapter \
    libwvdrmengine \
    qcrild_librilutils \
    qtibus \
    qtimutex \
    vendor.display.color@1.0 \
    vendor.display.color@1.1 \
    vendor.display.color@1.2 \
    vendor.display.postproc@1.0 \
    vendor.qti.data.factory@2.0 \
    vendor.qti.data.factory@2.1 \
    vendor.qti.data.factory@2.2 \
    vendor.qti.data.factory@2.3 \
    vendor.qti.data.mwqem@1.0 \
    vendor.qti.data.slm@1.0 \
    vendor.qti.gnss@1.0 \
    vendor.qti.gnss@1.1 \
    vendor.qti.gnss@1.2 \
    vendor.qti.gnss@2.0 \
    vendor.qti.gnss@2.1 \
    vendor.qti.gnss@3.0-service \
    vendor.qti.gnss@3.0 \
    vendor.qti.hardware.alarm@1.0 \
    vendor.qti.hardware.bluetooth_sar@1.0 \
    vendor.qti.hardware.cacert@1.0 \
    vendor.qti.hardware.data.cne.internal.api@1.0 \
    vendor.qti.hardware.data.cne.internal.constants@1.0 \
    vendor.qti.hardware.data.cne.internal.server@1.0 \
    vendor.qti.hardware.data.connection@1.0 \
    vendor.qti.hardware.data.connection@1.1 \
    vendor.qti.hardware.data.dynamicdds@1.0 \
    vendor.qti.hardware.data.iwlan@1.0 \
    vendor.qti.hardware.data.latency@1.0 \
    vendor.qti.hardware.data.lce@1.0 \
    vendor.qti.hardware.data.qmi@1.0 \
    vendor.qti.hardware.fm@1.0 \
    vendor.qti.hardware.mwqemadapter@1.0 \
    vendor.qti.hardware.radio.am@1.0 \
    vendor.qti.hardware.radio.atcmdfwd@1.0 \
    vendor.qti.hardware.radio.ims@1.0 \
    vendor.qti.hardware.radio.ims@1.1 \
    vendor.qti.hardware.radio.ims@1.2 \
    vendor.qti.hardware.radio.ims@1.3 \
    vendor.qti.hardware.radio.ims@1.4 \
    vendor.qti.hardware.radio.ims@1.5 \
    vendor.qti.hardware.radio.ims@1.6 \
    vendor.qti.hardware.radio.ims@1.7 \
    vendor.qti.hardware.radio.internal.deviceinfo@1.0 \
    vendor.qti.hardware.radio.lpa@1.0 \
    vendor.qti.hardware.radio.lpa@1.1 \
    vendor.qti.hardware.radio.qcrilhook@1.0 \
    vendor.qti.hardware.radio.qtiradio@1.0 \
    vendor.qti.hardware.radio.qtiradio@2.0 \
    vendor.qti.hardware.radio.qtiradio@2.1 \
    vendor.qti.hardware.radio.qtiradio@2.2 \
    vendor.qti.hardware.radio.qtiradio@2.3 \
    vendor.qti.hardware.radio.qtiradio@2.4 \
    vendor.qti.hardware.radio.uim@1.0 \
    vendor.qti.hardware.radio.uim@1.1 \
    vendor.qti.hardware.radio.uim@1.2 \
    vendor.qti.hardware.radio.uim_remote_client@1.0 \
    vendor.qti.hardware.radio.uim_remote_client@1.1 \
    vendor.qti.hardware.radio.uim_remote_client@1.2 \
    vendor.qti.hardware.radio.uim_remote_server@1.0 \
    vendor.qti.hardware.slmadapter@1.0 \
    vendor.qti.ims.callcapability@1.0 \
    vendor.qti.ims.callinfo@1.0 \
    vendor.qti.ims.factory@1.0 \
    vendor.qti.ims.factory@1.1 \
    vendor.qti.ims.rcsconfig@1.0 \
    vendor.qti.ims.rcsconfig@1.1 \
    vendor.qti.ims.rcsconfig@2.0 \
    vendor.qti.ims.rcsconfig@2.1 \
    vendor.qti.imsrtpservice@3.0-service-Impl \
    vendor.qti.imsrtpservice@3.0_vendor \
    vendor.qti.latency@2.0 \
    vendor.qti.latency@2.1 \
    libFastRPC_AUE_Forward_skel \
    libFastRPC_UTF_Forward_Qtc2_skel \
    libadsp_hvx_add_constant \
    libadsp_hvx_skel \
    libadsp_hvx_stats \
    libadsp_hvx_zzhdr_BGGR \
    libadsp_hvx_zzhdr_RGGB \
    libapps_mem_heap \
    libdspCV_skel \
    libfastcvadsp \
    libfastcvadsp_skel \
    com.qualcomm.qti.dpm.api@1.0 \
    lib-imscamera \
    lib-imsvideocodec \
    lib-imsvt \
    lib-imsvtextutils \
    lib-imsvtutils \
    libdiag_system \
    libdpmctmgr \
    libdpmfdmgr \
    libdpmframework \
    libdpmtcm \
    libimscamera_jni \
    libimsmedia_jni \
    vendor.qti.diaghal@1.0 \
    vendor.qti.imsrtpservice@3.0 \
    CneApp \
    IWlanService \
    TimeService \
    PowerOffAlarm \
    QtiTelephonyService \
    dpmserviceapp \
    ims \
    qcrilmsgtunnel \
    com.qti.dpmframework \
    dpmapi \
    qcrilhook \
    android.hardware.gnss@2.0-service-qti.xml \
    manifest_android.hardware.drm@1.3-service.widevine.xml \
    vendor.qti.gnss@3.0-service.xml \
    ATFWD-daemon \
    adpl \
    adsprpcd \
    cnd \
    dpmQmiMgr \
    energy-awareness \
    hvdcp_opti \
    android.hardware.bluetooth@1.0-service-qti \
    android.hardware.drm@1.3-service.widevine \
    android.hardware.gnss@2.0-service-qti \
    qcrild \
    vendor.display.color@1.0-service \
    vendor.qti.hardware.alarm@1.0-service \
    vendor.qti.hardware.perf@2.0-service \
    ims_rtp_daemon \
    imsdatadaemon \
    imsqmidaemon \
    imsrcsd \
    irsc_util \
    loc_launcher \
    lowi-server \
    mm-pp-dpps \
    mm-qcamera-daemon \
    msm_irqbalance \
    netmgrd \
    pm-proxy \
    pm-service \
    port-bridge \
    power_off_alarm \
    qrtr-lookup \
    qrtr-ns \
    qseecomd \
    qti \
    remosaic_daemon \
    rmt_storage \
    sensors.qti \
    tftp_server \
    thermal-engine \
    time_daemon \
    xtra-daemon \
    dpmd

PRODUCT_PACKAGES += \
    system_ext_priv-app_ims_lib_arm64_libimscamera_jni_so \
    system_ext_priv-app_ims_lib_arm64_libimsmedia_jni_so
